/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GpuType = IDL.Record({
  'id' : IDL.Nat,
  'tdp' : IDL.Nat,
  'performanceRating' : IDL.Float64,
  'name' : IDL.Text,
  'vram' : IDL.Text,
  'description' : IDL.Text,
  'series' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'releaseYear' : IDL.Nat,
  'condition' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGpu' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getFeaturedGpus' : IDL.Func([], [IDL.Vec(GpuType)], ['query']),
  'getGpu' : IDL.Func([IDL.Nat], [IDL.Opt(GpuType)], ['query']),
  'getGpus' : IDL.Func([], [IDL.Vec(GpuType)], ['query']),
  'removeGpu' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleFeatured' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateGpu' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GpuType = IDL.Record({
    'id' : IDL.Nat,
    'tdp' : IDL.Nat,
    'performanceRating' : IDL.Float64,
    'name' : IDL.Text,
    'vram' : IDL.Text,
    'description' : IDL.Text,
    'series' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'releaseYear' : IDL.Nat,
    'condition' : IDL.Text,
  });
  
  return IDL.Service({
    'addGpu' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getFeaturedGpus' : IDL.Func([], [IDL.Vec(GpuType)], ['query']),
    'getGpu' : IDL.Func([IDL.Nat], [IDL.Opt(GpuType)], ['query']),
    'getGpus' : IDL.Func([], [IDL.Vec(GpuType)], ['query']),
    'removeGpu' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleFeatured' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateGpu' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };