/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GpuType {
  'id' : bigint,
  'tdp' : bigint,
  'performanceRating' : number,
  'name' : string,
  'vram' : string,
  'description' : string,
  'series' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'brand' : string,
  'price' : bigint,
  'releaseYear' : bigint,
  'condition' : string,
}
export interface _SERVICE {
  'addGpu' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      string,
      number,
      string,
      bigint,
      bigint,
      string,
    ],
    bigint
  >,
  'getFeaturedGpus' : ActorMethod<[], Array<GpuType>>,
  'getGpu' : ActorMethod<[bigint], [] | [GpuType]>,
  'getGpus' : ActorMethod<[], Array<GpuType>>,
  'removeGpu' : ActorMethod<[bigint], boolean>,
  'toggleFeatured' : ActorMethod<[bigint], boolean>,
  'updateGpu' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      string,
      number,
      string,
      bigint,
      bigint,
      string,
    ],
    boolean
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];